// Code generated by protoc-gen-go.
// source: protocol/message/message_betting.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type BetType int32

const (
	BetType_Ante       BetType = 1
	BetType_BringIn    BetType = 2
	BetType_SmallBlind BetType = 3
	BetType_BigBlind   BetType = 4
	BetType_GuestBlind BetType = 5
	BetType_Straddle   BetType = 6
	BetType_Raise      BetType = 7
	BetType_Call       BetType = 8
	BetType_Check      BetType = 9
	BetType_Fold       BetType = 10
	BetType_Discard    BetType = 11
	BetType_StandPat   BetType = 12
	BetType_Show       BetType = 13
	BetType_Muck       BetType = 14
)

var BetType_name = map[int32]string{
	1:  "Ante",
	2:  "BringIn",
	3:  "SmallBlind",
	4:  "BigBlind",
	5:  "GuestBlind",
	6:  "Straddle",
	7:  "Raise",
	8:  "Call",
	9:  "Check",
	10: "Fold",
	11: "Discard",
	12: "StandPat",
	13: "Show",
	14: "Muck",
}
var BetType_value = map[string]int32{
	"Ante":       1,
	"BringIn":    2,
	"SmallBlind": 3,
	"BigBlind":   4,
	"GuestBlind": 5,
	"Straddle":   6,
	"Raise":      7,
	"Call":       8,
	"Check":      9,
	"Fold":       10,
	"Discard":    11,
	"StandPat":   12,
	"Show":       13,
	"Muck":       14,
}

func (x BetType) Enum() *BetType {
	p := new(BetType)
	*p = x
	return p
}
func (x BetType) String() string {
	return proto.EnumName(BetType_name, int32(x))
}
func (x BetType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *BetType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BetType_value, data, "BetType")
	if err != nil {
		return err
	}
	*x = BetType(value)
	return nil
}

type BetRange struct {
	Call             *float64 `protobuf:"fixed64,1,req" json:"Call,omitempty"`
	Min              *float64 `protobuf:"fixed64,2,req" json:"Min,omitempty"`
	Max              *float64 `protobuf:"fixed64,3,req" json:"Max,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *BetRange) Reset()         { *this = BetRange{} }
func (this *BetRange) String() string { return proto.CompactTextString(this) }
func (*BetRange) ProtoMessage()       {}

func (this *BetRange) GetCall() float64 {
	if this != nil && this.Call != nil {
		return *this.Call
	}
	return 0
}

func (this *BetRange) GetMin() float64 {
	if this != nil && this.Min != nil {
		return *this.Min
	}
	return 0
}

func (this *BetRange) GetMax() float64 {
	if this != nil && this.Max != nil {
		return *this.Max
	}
	return 0
}

type RequireBet struct {
	Pos              *int32    `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	BetRange         *BetRange `protobuf:"bytes,2,req" json:"BetRange,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (this *RequireBet) Reset()         { *this = RequireBet{} }
func (this *RequireBet) String() string { return proto.CompactTextString(this) }
func (*RequireBet) ProtoMessage()       {}

func (this *RequireBet) GetPos() int32 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

func (this *RequireBet) GetBetRange() *BetRange {
	if this != nil {
		return this.BetRange
	}
	return nil
}

type Bet struct {
	Type             *BetType `protobuf:"varint,1,req,enum=message.BetType" json:"Type,omitempty"`
	Amount           *float64 `protobuf:"fixed64,2,opt" json:"Amount,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Bet) Reset()         { *this = Bet{} }
func (this *Bet) String() string { return proto.CompactTextString(this) }
func (*Bet) ProtoMessage()       {}

func (this *Bet) GetType() BetType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *Bet) GetAmount() float64 {
	if this != nil && this.Amount != nil {
		return *this.Amount
	}
	return 0
}

type AddBet struct {
	Pos              *int32 `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	Bet              *Bet   `protobuf:"bytes,2,req" json:"Bet,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *AddBet) Reset()         { *this = AddBet{} }
func (this *AddBet) String() string { return proto.CompactTextString(this) }
func (*AddBet) ProtoMessage()       {}

func (this *AddBet) GetPos() int32 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

func (this *AddBet) GetBet() *Bet {
	if this != nil {
		return this.Bet
	}
	return nil
}

type BettingComplete struct {
	Pot              *float64 `protobuf:"fixed64,1,req" json:"Pot,omitempty"`
	Rake             *float64 `protobuf:"fixed64,2,req" json:"Rake,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *BettingComplete) Reset()         { *this = BettingComplete{} }
func (this *BettingComplete) String() string { return proto.CompactTextString(this) }
func (*BettingComplete) ProtoMessage()       {}

func (this *BettingComplete) GetPot() float64 {
	if this != nil && this.Pot != nil {
		return *this.Pot
	}
	return 0
}

func (this *BettingComplete) GetRake() float64 {
	if this != nil && this.Rake != nil {
		return *this.Rake
	}
	return 0
}

func init() {
	proto.RegisterEnum("message.BetType", BetType_name, BetType_value)
}
