// Code generated by protoc-gen-go.
// source: protocol/message/message_table.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SeatState int32

const (
	SeatState_Empty  SeatState = 0
	SeatState_Taken  SeatState = 1
	SeatState_Ready  SeatState = 2
	SeatState_WaitBB SeatState = 3
	SeatState_PostBB SeatState = 4
	SeatState_Play   SeatState = 5
	SeatState_PutBet SeatState = 6
	SeatState_AllIn  SeatState = 7
	SeatState_Folded SeatState = 8
	SeatState_Auto   SeatState = 9
	SeatState_Kicked SeatState = 10
	SeatState_Busted SeatState = 11
	SeatState_Away   SeatState = 12
	SeatState_Idle   SeatState = 13
)

var SeatState_name = map[int32]string{
	0:  "Empty",
	1:  "Taken",
	2:  "Ready",
	3:  "WaitBB",
	4:  "PostBB",
	5:  "Play",
	6:  "PutBet",
	7:  "AllIn",
	8:  "Folded",
	9:  "Auto",
	10: "Kicked",
	11: "Busted",
	12: "Away",
	13: "Idle",
}
var SeatState_value = map[string]int32{
	"Empty":  0,
	"Taken":  1,
	"Ready":  2,
	"WaitBB": 3,
	"PostBB": 4,
	"Play":   5,
	"PutBet": 6,
	"AllIn":  7,
	"Folded": 8,
	"Auto":   9,
	"Kicked": 10,
	"Busted": 11,
	"Away":   12,
	"Idle":   13,
}

func (x SeatState) Enum() *SeatState {
	p := new(SeatState)
	*p = x
	return p
}
func (x SeatState) String() string {
	return proto.EnumName(SeatState_name, int32(x))
}
func (x SeatState) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *SeatState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SeatState_value, data, "SeatState")
	if err != nil {
		return err
	}
	*x = SeatState(value)
	return nil
}

type MoveButton struct {
	Pos              *int32 `protobuf:"varint,1,req" json:"Pos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MoveButton) Reset()         { *m = MoveButton{} }
func (m *MoveButton) String() string { return proto.CompactTextString(m) }
func (*MoveButton) ProtoMessage()    {}

func (m *MoveButton) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type JoinTable struct {
	Player           *string  `protobuf:"bytes,1,req" json:"Player,omitempty"`
	Pos              *int32   `protobuf:"varint,2,req" json:"Pos,omitempty"`
	Amount           *float64 `protobuf:"fixed64,3,req" json:"Amount,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *JoinTable) Reset()         { *m = JoinTable{} }
func (m *JoinTable) String() string { return proto.CompactTextString(m) }
func (*JoinTable) ProtoMessage()    {}

func (m *JoinTable) GetPlayer() string {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return ""
}

func (m *JoinTable) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *JoinTable) GetAmount() float64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

type LeaveTable struct {
	Player           *string `protobuf:"bytes,1,req" json:"Player,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LeaveTable) Reset()         { *m = LeaveTable{} }
func (m *LeaveTable) String() string { return proto.CompactTextString(m) }
func (*LeaveTable) ProtoMessage()    {}

func (m *LeaveTable) GetPlayer() string {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return ""
}

type SitOut struct {
	Pos              *int32 `protobuf:"varint,1,req" json:"Pos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SitOut) Reset()         { *m = SitOut{} }
func (m *SitOut) String() string { return proto.CompactTextString(m) }
func (*SitOut) ProtoMessage()    {}

func (m *SitOut) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type ComeBack struct {
	Pos              *int32 `protobuf:"varint,1,req" json:"Pos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ComeBack) Reset()         { *m = ComeBack{} }
func (m *ComeBack) String() string { return proto.CompactTextString(m) }
func (*ComeBack) ProtoMessage()    {}

func (m *ComeBack) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

type Seat struct {
	Pos              *int32     `protobuf:"varint,1,req" json:"Pos,omitempty"`
	State            *SeatState `protobuf:"varint,2,opt,enum=message.SeatState" json:"State,omitempty"`
	Stack            *float64   `protobuf:"fixed64,3,opt" json:"Stack,omitempty"`
	Bet              *float64   `protobuf:"fixed64,4,opt" json:"Bet,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (m *Seat) Reset()         { *m = Seat{} }
func (m *Seat) String() string { return proto.CompactTextString(m) }
func (*Seat) ProtoMessage()    {}

func (m *Seat) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *Seat) GetState() SeatState {
	if m != nil && m.State != nil {
		return *m.State
	}
	return 0
}

func (m *Seat) GetStack() float64 {
	if m != nil && m.Stack != nil {
		return *m.Stack
	}
	return 0
}

func (m *Seat) GetBet() float64 {
	if m != nil && m.Bet != nil {
		return *m.Bet
	}
	return 0
}

type Table struct {
	Id               *string `protobuf:"bytes,1,req" json:"Id,omitempty"`
	Size             *int32  `protobuf:"varint,2,req" json:"Size,omitempty"`
	Button           *int32  `protobuf:"varint,3,req" json:"Button,omitempty"`
	Seats            []*Seat `protobuf:"bytes,4,rep" json:"Seats,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Table) Reset()         { *m = Table{} }
func (m *Table) String() string { return proto.CompactTextString(m) }
func (*Table) ProtoMessage()    {}

func (m *Table) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Table) GetSize() int32 {
	if m != nil && m.Size != nil {
		return *m.Size
	}
	return 0
}

func (m *Table) GetButton() int32 {
	if m != nil && m.Button != nil {
		return *m.Button
	}
	return 0
}

func (m *Table) GetSeats() []*Seat {
	if m != nil {
		return m.Seats
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.SeatState", SeatState_name, SeatState_value)
}
