// Code generated by protoc-gen-go.
// source: protocol/message/message_deal.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type DealType int32

const (
	DealType_Board DealType = 0
	DealType_Hole  DealType = 1
	DealType_Door  DealType = 2
)

var DealType_name = map[int32]string{
	0: "Board",
	1: "Hole",
	2: "Door",
}
var DealType_value = map[string]int32{
	"Board": 0,
	"Hole":  1,
	"Door":  2,
}

func (x DealType) Enum() *DealType {
	p := new(DealType)
	*p = x
	return p
}
func (x DealType) String() string {
	return proto.EnumName(DealType_name, int32(x))
}
func (x DealType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *DealType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(DealType_value, data, "DealType")
	if err != nil {
		return err
	}
	*x = DealType(value)
	return nil
}

type DealCards struct {
	Pos              *int32    `protobuf:"varint,1,req" json:"Pos,omitempty"`
	Cards            []byte    `protobuf:"bytes,2,req" json:"Cards,omitempty"`
	Type             *DealType `protobuf:"varint,3,req,enum=message.DealType" json:"Type,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (this *DealCards) Reset()         { *this = DealCards{} }
func (this *DealCards) String() string { return proto.CompactTextString(this) }
func (*DealCards) ProtoMessage()       {}

func (this *DealCards) GetPos() int32 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

func (this *DealCards) GetCards() []byte {
	if this != nil {
		return this.Cards
	}
	return nil
}

func (this *DealCards) GetType() DealType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

type RequireDiscard struct {
	Pos              *int32 `protobuf:"varint,1,req" json:"Pos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *RequireDiscard) Reset()         { *this = RequireDiscard{} }
func (this *RequireDiscard) String() string { return proto.CompactTextString(this) }
func (*RequireDiscard) ProtoMessage()       {}

func (this *RequireDiscard) GetPos() int32 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

type Discarded struct {
	Pos              *int32 `protobuf:"varint,1,req" json:"Pos,omitempty"`
	Num              *int32 `protobuf:"varint,2,req" json:"Num,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Discarded) Reset()         { *this = Discarded{} }
func (this *Discarded) String() string { return proto.CompactTextString(this) }
func (*Discarded) ProtoMessage()       {}

func (this *Discarded) GetPos() int32 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

func (this *Discarded) GetNum() int32 {
	if this != nil && this.Num != nil {
		return *this.Num
	}
	return 0
}

type DiscardCards struct {
	Pos              *int32 `protobuf:"varint,1,req" json:"Pos,omitempty"`
	Cards            []byte `protobuf:"bytes,2,req" json:"Cards,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *DiscardCards) Reset()         { *this = DiscardCards{} }
func (this *DiscardCards) String() string { return proto.CompactTextString(this) }
func (*DiscardCards) ProtoMessage()       {}

func (this *DiscardCards) GetPos() int32 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

func (this *DiscardCards) GetCards() []byte {
	if this != nil {
		return this.Cards
	}
	return nil
}

func init() {
	proto.RegisterEnum("message.DealType", DealType_name, DealType_value)
}
