// Code generated by protoc-gen-go.
// source: protocol/message.proto
// DO NOT EDIT!

package protocol

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ErrorMessage struct {
	Message          *string `protobuf:"bytes,1,req" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ErrorMessage) Reset()         { *this = ErrorMessage{} }
func (this *ErrorMessage) String() string { return proto.CompactTextString(this) }
func (*ErrorMessage) ProtoMessage()       {}

func (this *ErrorMessage) GetMessage() string {
	if this != nil && this.Message != nil {
		return *this.Message
	}
	return ""
}

type ChatMessage struct {
	Pos              *int32  `protobuf:"varint,1,req,name=pos" json:"pos,omitempty"`
	Message          *string `protobuf:"bytes,2,req" json:"Message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ChatMessage) Reset()         { *this = ChatMessage{} }
func (this *ChatMessage) String() string { return proto.CompactTextString(this) }
func (*ChatMessage) ProtoMessage()       {}

func (this *ChatMessage) GetPos() int32 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

func (this *ChatMessage) GetMessage() string {
	if this != nil && this.Message != nil {
		return *this.Message
	}
	return ""
}

func init() {
}
