// Code generated by protoc-gen-go.
// source: protocol/message/message_play.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type GameType int32

const (
	GameType_Texas    GameType = 0
	GameType_Omaha    GameType = 1
	GameType_Omaha8   GameType = 2
	GameType_Stud     GameType = 3
	GameType_Stud8    GameType = 4
	GameType_Razz     GameType = 9
	GameType_London   GameType = 10
	GameType_FiveCard GameType = 11
	GameType_Single27 GameType = 12
	GameType_Triple27 GameType = 13
	GameType_Badugi   GameType = 14
)

var GameType_name = map[int32]string{
	0:  "Texas",
	1:  "Omaha",
	2:  "Omaha8",
	3:  "Stud",
	4:  "Stud8",
	9:  "Razz",
	10: "London",
	11: "FiveCard",
	12: "Single27",
	13: "Triple27",
	14: "Badugi",
}
var GameType_value = map[string]int32{
	"Texas":    0,
	"Omaha":    1,
	"Omaha8":   2,
	"Stud":     3,
	"Stud8":    4,
	"Razz":     9,
	"London":   10,
	"FiveCard": 11,
	"Single27": 12,
	"Triple27": 13,
	"Badugi":   14,
}

func (x GameType) Enum() *GameType {
	p := new(GameType)
	*p = x
	return p
}
func (x GameType) String() string {
	return proto.EnumName(GameType_name, int32(x))
}
func (x GameType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *GameType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameType_value, data, "GameType")
	if err != nil {
		return err
	}
	*x = GameType(value)
	return nil
}

type GameLimit int32

const (
	GameLimit_NoLimit    GameLimit = 0
	GameLimit_PotLimit   GameLimit = 1
	GameLimit_FixedLimit GameLimit = 2
)

var GameLimit_name = map[int32]string{
	0: "NoLimit",
	1: "PotLimit",
	2: "FixedLimit",
}
var GameLimit_value = map[string]int32{
	"NoLimit":    0,
	"PotLimit":   1,
	"FixedLimit": 2,
}

func (x GameLimit) Enum() *GameLimit {
	p := new(GameLimit)
	*p = x
	return p
}
func (x GameLimit) String() string {
	return proto.EnumName(GameLimit_name, int32(x))
}
func (x GameLimit) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *GameLimit) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(GameLimit_value, data, "GameLimit")
	if err != nil {
		return err
	}
	*x = GameLimit(value)
	return nil
}

type SeatState int32

const (
	SeatState_Empty           SeatState = 0
	SeatState_Reserved        SeatState = 1
	SeatState_Ready           SeatState = 2
	SeatState_WaitingBigBlind SeatState = 3
	SeatState_PostingBigBlind SeatState = 4
	SeatState_Playing         SeatState = 5
	SeatState_Betting         SeatState = 6
	SeatState_Allin           SeatState = 7
	SeatState_Folded          SeatState = 8
	SeatState_Autoplay        SeatState = 9
	SeatState_OutOfStack      SeatState = 10
	SeatState_OutOfTournament SeatState = 11
	SeatState_NotPlaying      SeatState = 12
	SeatState_Disconnected    SeatState = 13
)

var SeatState_name = map[int32]string{
	0:  "Empty",
	1:  "Reserved",
	2:  "Ready",
	3:  "WaitingBigBlind",
	4:  "PostingBigBlind",
	5:  "Playing",
	6:  "Betting",
	7:  "Allin",
	8:  "Folded",
	9:  "Autoplay",
	10: "OutOfStack",
	11: "OutOfTournament",
	12: "NotPlaying",
	13: "Disconnected",
}
var SeatState_value = map[string]int32{
	"Empty":           0,
	"Reserved":        1,
	"Ready":           2,
	"WaitingBigBlind": 3,
	"PostingBigBlind": 4,
	"Playing":         5,
	"Betting":         6,
	"Allin":           7,
	"Folded":          8,
	"Autoplay":        9,
	"OutOfStack":      10,
	"OutOfTournament": 11,
	"NotPlaying":      12,
	"Disconnected":    13,
}

func (x SeatState) Enum() *SeatState {
	p := new(SeatState)
	*p = x
	return p
}
func (x SeatState) String() string {
	return proto.EnumName(SeatState_name, int32(x))
}
func (x SeatState) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *SeatState) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SeatState_value, data, "SeatState")
	if err != nil {
		return err
	}
	*x = SeatState(value)
	return nil
}

type Seat struct {
	Pos              *int32     `protobuf:"varint,1,req" json:"Pos,omitempty"`
	State            *SeatState `protobuf:"varint,2,opt,enum=message.SeatState" json:"State,omitempty"`
	Stack            *float64   `protobuf:"fixed64,3,opt" json:"Stack,omitempty"`
	Bet              *float64   `protobuf:"fixed64,4,opt" json:"Bet,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (this *Seat) Reset()         { *this = Seat{} }
func (this *Seat) String() string { return proto.CompactTextString(this) }
func (*Seat) ProtoMessage()       {}

func (this *Seat) GetPos() int32 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

func (this *Seat) GetState() SeatState {
	if this != nil && this.State != nil {
		return *this.State
	}
	return 0
}

func (this *Seat) GetStack() float64 {
	if this != nil && this.Stack != nil {
		return *this.Stack
	}
	return 0
}

func (this *Seat) GetBet() float64 {
	if this != nil && this.Bet != nil {
		return *this.Bet
	}
	return 0
}

type Table struct {
	Id               *string `protobuf:"bytes,1,req" json:"Id,omitempty"`
	Size             *int32  `protobuf:"varint,2,req" json:"Size,omitempty"`
	Button           *int32  `protobuf:"varint,3,req" json:"Button,omitempty"`
	Seats            []*Seat `protobuf:"bytes,4,rep" json:"Seats,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Table) Reset()         { *this = Table{} }
func (this *Table) String() string { return proto.CompactTextString(this) }
func (*Table) ProtoMessage()       {}

func (this *Table) GetId() string {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return ""
}

func (this *Table) GetSize() int32 {
	if this != nil && this.Size != nil {
		return *this.Size
	}
	return 0
}

func (this *Table) GetButton() int32 {
	if this != nil && this.Button != nil {
		return *this.Button
	}
	return 0
}

func (this *Table) GetSeats() []*Seat {
	if this != nil {
		return this.Seats
	}
	return nil
}

type Game struct {
	Type             *GameType  `protobuf:"varint,1,req,enum=message.GameType" json:"Type,omitempty"`
	Limit            *GameLimit `protobuf:"varint,2,req,enum=message.GameLimit" json:"Limit,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (this *Game) Reset()         { *this = Game{} }
func (this *Game) String() string { return proto.CompactTextString(this) }
func (*Game) ProtoMessage()       {}

func (this *Game) GetType() GameType {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return 0
}

func (this *Game) GetLimit() GameLimit {
	if this != nil && this.Limit != nil {
		return *this.Limit
	}
	return 0
}

type Stake struct {
	BigBlind         *float64 `protobuf:"fixed64,1,req" json:"BigBlind,omitempty"`
	SmallBlind       *float64 `protobuf:"fixed64,2,opt" json:"SmallBlind,omitempty"`
	Ante             *float64 `protobuf:"fixed64,3,opt" json:"Ante,omitempty"`
	BringIn          *float64 `protobuf:"fixed64,4,opt" json:"BringIn,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Stake) Reset()         { *this = Stake{} }
func (this *Stake) String() string { return proto.CompactTextString(this) }
func (*Stake) ProtoMessage()       {}

func (this *Stake) GetBigBlind() float64 {
	if this != nil && this.BigBlind != nil {
		return *this.BigBlind
	}
	return 0
}

func (this *Stake) GetSmallBlind() float64 {
	if this != nil && this.SmallBlind != nil {
		return *this.SmallBlind
	}
	return 0
}

func (this *Stake) GetAnte() float64 {
	if this != nil && this.Ante != nil {
		return *this.Ante
	}
	return 0
}

func (this *Stake) GetBringIn() float64 {
	if this != nil && this.BringIn != nil {
		return *this.BringIn
	}
	return 0
}

type Deal struct {
	Pot              *float64 `protobuf:"fixed64,1,req" json:"Pot,omitempty"`
	Board            []int32  `protobuf:"varint,2,rep" json:"Board,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *Deal) Reset()         { *this = Deal{} }
func (this *Deal) String() string { return proto.CompactTextString(this) }
func (*Deal) ProtoMessage()       {}

func (this *Deal) GetPot() float64 {
	if this != nil && this.Pot != nil {
		return *this.Pot
	}
	return 0
}

func (this *Deal) GetBoard() []int32 {
	if this != nil {
		return this.Board
	}
	return nil
}

type Play struct {
	Game             *Game  `protobuf:"bytes,1,req" json:"Game,omitempty"`
	Table            *Table `protobuf:"bytes,2,req" json:"Table,omitempty"`
	Stake            *Stake `protobuf:"bytes,3,req" json:"Stake,omitempty"`
	Deal             *Deal  `protobuf:"bytes,4,req" json:"Deal,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Play) Reset()         { *this = Play{} }
func (this *Play) String() string { return proto.CompactTextString(this) }
func (*Play) ProtoMessage()       {}

func (this *Play) GetGame() *Game {
	if this != nil {
		return this.Game
	}
	return nil
}

func (this *Play) GetTable() *Table {
	if this != nil {
		return this.Table
	}
	return nil
}

func (this *Play) GetStake() *Stake {
	if this != nil {
		return this.Stake
	}
	return nil
}

func (this *Play) GetDeal() *Deal {
	if this != nil {
		return this.Deal
	}
	return nil
}

type PlayStart struct {
	Play             *Play  `protobuf:"bytes,1,opt" json:"Play,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *PlayStart) Reset()         { *this = PlayStart{} }
func (this *PlayStart) String() string { return proto.CompactTextString(this) }
func (*PlayStart) ProtoMessage()       {}

func (this *PlayStart) GetPlay() *Play {
	if this != nil {
		return this.Play
	}
	return nil
}

type PlayStop struct {
	Play             *Play  `protobuf:"bytes,1,opt" json:"Play,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *PlayStop) Reset()         { *this = PlayStop{} }
func (this *PlayStop) String() string { return proto.CompactTextString(this) }
func (*PlayStop) ProtoMessage()       {}

func (this *PlayStop) GetPlay() *Play {
	if this != nil {
		return this.Play
	}
	return nil
}

type StreetStart struct {
	Name             *string `protobuf:"bytes,1,req" json:"Name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *StreetStart) Reset()         { *this = StreetStart{} }
func (this *StreetStart) String() string { return proto.CompactTextString(this) }
func (*StreetStart) ProtoMessage()       {}

func (this *StreetStart) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("message.GameType", GameType_name, GameType_value)
	proto.RegisterEnum("message.GameLimit", GameLimit_name, GameLimit_value)
	proto.RegisterEnum("message.SeatState", SeatState_name, SeatState_value)
}
