// Code generated by protoc-gen-go.
// source: protocol/message/message_table.proto
// DO NOT EDIT!

package message

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

// MoveButton - table move button
type MoveButton struct {
	Pos              *int32 `protobuf:"varint,1,req" json:"Pos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MoveButton) Reset()         { *m = MoveButton{} }
func (m *MoveButton) String() string { return proto.CompactTextString(m) }
func (*MoveButton) ProtoMessage()    {}

func (m *MoveButton) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

// JoinTable - player join table
type JoinTable struct {
	Player           *string  `protobuf:"bytes,1,req" json:"Player,omitempty"`
	Pos              *int32   `protobuf:"varint,2,req" json:"Pos,omitempty"`
	Amount           *float64 `protobuf:"fixed64,3,req" json:"Amount,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *JoinTable) Reset()         { *m = JoinTable{} }
func (m *JoinTable) String() string { return proto.CompactTextString(m) }
func (*JoinTable) ProtoMessage()    {}

func (m *JoinTable) GetPlayer() string {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return ""
}

func (m *JoinTable) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func (m *JoinTable) GetAmount() float64 {
	if m != nil && m.Amount != nil {
		return *m.Amount
	}
	return 0
}

// LeaveTable - player leave table
type LeaveTable struct {
	Player           *string `protobuf:"bytes,1,req" json:"Player,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LeaveTable) Reset()         { *m = LeaveTable{} }
func (m *LeaveTable) String() string { return proto.CompactTextString(m) }
func (*LeaveTable) ProtoMessage()    {}

func (m *LeaveTable) GetPlayer() string {
	if m != nil && m.Player != nil {
		return *m.Player
	}
	return ""
}

// SitOut - player sit out
type SitOut struct {
	Pos              *int32 `protobuf:"varint,1,req" json:"Pos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SitOut) Reset()         { *m = SitOut{} }
func (m *SitOut) String() string { return proto.CompactTextString(m) }
func (*SitOut) ProtoMessage()    {}

func (m *SitOut) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

// ComeBack - player come back
type ComeBack struct {
	Pos              *int32 `protobuf:"varint,1,req" json:"Pos,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *ComeBack) Reset()         { *m = ComeBack{} }
func (m *ComeBack) String() string { return proto.CompactTextString(m) }
func (*ComeBack) ProtoMessage()    {}

func (m *ComeBack) GetPos() int32 {
	if m != nil && m.Pos != nil {
		return *m.Pos
	}
	return 0
}

func init() {
}
